services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    restart: always
    user: root
    ports:
      - "9090:8080"  
      - "50000:50000"  # Fix: Keep agent communication port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cicd-network

  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always
    ports:
      - "6060:80"
    volumes:
      - ./app:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cicd-network

networks:
  cicd-network:
    driver: bridge

volumes:
  jenkins_home:
    driver: local
